source 'https://rubygems.org'

# Sort ruby gems by alphabet please!
# Always use version on rubygem to prevent deprecate gem feature on new installation

gem 'activesupport'
gem 'artii', '~> 2.1', '>= 2.1.1'
# gem 'bukalapak_web_automation', git: 'git@git.gitlab.cloud.bukalapak.io:bukalapak/bukalapak_web_automation.git', glob: 'web.gemspec'
gem 'bson_ext'
gem 'capybara', '3.18.0'
gem 'capybara-screenshot', '~> 1.0', '>= 1.0.23'
gem 'cassandra-driver'
gem 'colorize', '~> 0.8.1'
gem 'cucumber', '~> 3.1'
gem 'danger', '~> 6.3', '>= 6.3.1'
gem 'dotenv', '~> 2.7.5'
gem 'faker', :git => 'https://github.com/stympy/faker.git', :branch => 'master'
gem 'faraday', '~> 0.16.2'
gem 'fileutils', '~> 1.4', '>= 1.4.1'
gem 'geckodriver-helper', '~> 0.0.5'
gem 'headless', '~> 2.3', '>= 2.3.1'
gem 'highline', '~> 1.7', '>= 1.7.8'
gem 'httparty', '~> 0.18.0'
gem 'jsonpath', '~> 1.0', '>= 1.0.5'
gem 'json', '1.8.5'
gem 'multipart-post'
gem 'net-scp', '~> 2.0'
gem 'net-ssh', '~> 5.2'
gem 'nokogiri', '~> 1.7', '>= 1.7.0.1'
# gem 'pronto', '~> 0.9.5'
# gem 'pronto-flay', '~> 0.9.0', require: false
# gem 'pronto-rubocop', '~> 0.9.1', require: false
gem 'redis', '3.3.1'
gem 'rake', '~> 12.3.3'
gem 'report_builder'
gem 'rotp', '5.1.0'
gem 'rspec', '~> 3.9'
gem 'rspec-retry', '~> 0.4.5'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.4'
gem 'site_prism', '~> 3.4.2'
gem 'sinatra', '1.3.1'
gem 'slack-incoming-webhooks', '0.3.0'
gem 'telegramAPI', '~> 1.4', '>= 1.4.2'
gem 'wannabe_bool', '~> 0.7.1'
gem 'webdrivers', '~> 4.0'
